#!/bin/bash

export http_proxy='http://127.0.0.1:8123'
export https_proxy='http://127.0.0.1:8123'
wget https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt



gfwlist2pac -i gfwlist.txt -f /usr/share/polipo/www/autoproxy.pac -p 'PROXY 192.168.55.1:8123' --user-rule gfw-my-rules
